version: '3'

services:
  cloudinary:
    container_name: cloudinary
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
        - ./example:/example
    environment:
      CLOUDINARY_URL: ${CLOUDINARY_URL}
